# Generated by Django 2.2.5 on 2019-09-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190926_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('mail', 'Male'), ('female', 'FeMale'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
